### ISSUE TITLE
Remove Cloudify Manager bootstrap references

### ISSUE THREAD

**Issue by joshuap-cfy** [cloudify-cosmo/cloudify-vsphere-plugin#102]
I don't understand why this plugin doc references a way to bootstrap a Cloudify Manager. I think this reference should be removed since we are doing RPM and shell scripts based installs now.

I think a basic example like nodecellar should be listed in tests:
https://github.com/cloudify-cosmo/cloudify-vsphere-plugin/blob/2.4.0/examples/blueprint.yaml.example

Why are we listing Manager bootstrap inputs in this plugin:
manager_server_template
manager_server_cpus
manager_server_memory
manager_server_user
manager_server_user_home

I will most likely just launch a couple vm(s) (for CFY CLI and Mgr) manually and then use the RPM or shell script based installer.

**Comment by EarthmanT** [comment]
I don't see where these links are mentioned in the docs.
