### ISSUE TITLE
Error removing multiple network adapters from a VM.

### ISSUE THREAD

**Issue by jp1-msw** [cloudify-cosmo/cloudify-vsphere-plugin#116]
The code at https://github.com/cloudify-cosmo/cloudify-vsphere-plugin/blob/master/vsphere_plugin_common/__init__.py#L1427-1436 only seems to work when removing a single network adapter. Multiple adapters can be removed by repeatedly removing adapters one at a time, but adding more than one adapter to the list `devices` causes the reconfigure VM task to fail. 

Hence when Cloudify tries to deploy a VM from a template with multiple network adapters, the deploy fails as the network adapters aren't removed by this code.

**Comment by 0lvin** [comment]
Could you recheck issue with [2.17.0](08276bef8bfbe451ef3ae479a4a33bc2fedaa06a) release and postpone_delete_networks flag? Look to [other_vm.yaml](https://github.com/cloudify-cosmo/cloudify-vsphere-plugin/blob/2.17.0/system_tests/resources/linux/other_vm.yaml) as example.

**Comment by 0lvin** [comment]
Could your reopen if you still face such error?
