### ISSUE TITLE
Add support for putting vm's in folders

### ISSUE THREAD

**Issue by treyormsbee-interop** [cloudify-cosmo/cloudify-vsphere-plugin#124]
All vm's are created at the root level in vcenter.  Folders should be able to be specified for a deployment.

**Comment by EarthmanT** [comment]
We have added this as a feature request in our internal Jira: https://cloudifysource.atlassian.net/browse/CY-1117.

**Comment by 0lvin** [comment]
Will be added in next 2.13.0 release.

**Comment by 0lvin** [comment]
Implemented in [2.13.0](https://github.com/cloudify-cosmo/cloudify-vsphere-plugin/releases/tag/2.13.0)
